### PR TITLE
Voice

### PR DESCRIPTION
**Pull request by Megidd**
Users would be able to upload their voice recordings to the database.

### CODE REVIEW

**Comment by Megidd** [comment]
# Note for myself

1. Don't start with code.
2. But start with product UX/UI.
3. Then dig deeper into code.

**Comment by Megidd** [comment]
A button to sync voices with the database:

1. Add new voices to database.
2. Delete removed voices from database.

Screenshot_20220807_162728

**Comment by Megidd** [comment]
After making changes to back-end database table models, to see the changes, run:

```bash
i7:/home/mediacms.io/mediacms # docker-compose -f docker-compose-dev.yaml exec -T web python manage.py makemigrations
i7:/home/mediacms.io/mediacms # docker-compose -f docker-compose-dev.yaml restart web
```

image

**Comment by Megidd** [comment]
How to create admin - superuser - if you forgot the credentials:

```bash
i7:/home/mediacms.io/mediacms # docker-compose -f docker-compose-dev.yaml exec web python manage.py createsuperuser
```

Don't use `exec` with ` -T` flag. Since a TTY is required to interactively enter username and password.

image

**Comment by Megidd** [comment]
# Initial test

## Voices added to database

Three voices are added to a video/media by admin panel for managing database:

Screenshot_20220810_200635

## Voices fetched for the media

The voices corresponding to the video/media are fetched and available inside DAW:

Screenshot_20220810_200716

**Comment by Megidd** [comment]
# Test

The new voices are added to the database now:

Screenshot_20220812_163127

**Comment by Micrufun** [comment]
# Deploy changes

Pull new commits by Git. Then, if server is not up, bring it up:

```bash
sudo su
cd /home/mediacms.io/mediacms/
/usr/local/bin/docker-compose -f docker-compose-letsencrypt.yaml up -d
```

Deploy changes on server after modifying database table models:

```bash
sudo su
/usr/local/bin/docker-compose exec -T web python manage.py makemigrations
/usr/local/bin/docker-compose exec -T web python manage.py migrate
/usr/local/bin/docker-compose restart web celery_worker celery_beat
```

Adding admin to admin panel:

```bash
sudo su
/usr/local/bin/docker-compose exec web python manage.py createsuperuser
```
If Django version is messed up by playing around with `python -m pip install ...`, it can restored by:

```bash
sudo su
/usr/local/bin/docker-compose exec web python -m pip install -r requirements.txt
```

**Pull request merged**
