### PR TITLE
DAW

### PR DESCRIPTION
**Pull request by ghost**
Integrate digital audio workstation i.e. DAW.

### CODE REVIEW

**Comment by Micrufun** [comment]
`DAW placeholder` text is *not* showing up on UI. Why?

**Comment by Micrufun** [comment]
Now *DAW placeholder* is displayed at a proper location:

image

**Comment by Micrufun** [comment]
Now a primitive DAW preview is shown next to the video.

# Small screen width

DAW is below video.

image

# Large screen width

DAW is at right side of the video.

image

**Comment by Micrufun** [comment]
It's tried to follow this example:

https://github.com/naomiaro/waveform-playlist/blob/main/examples/basic-nextjs/pages/index.js

But this error is received:

> Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> 

image

**Comment by Micrufun** [comment]
The previous error got resolved by:

https://stackoverflow.com/a/71297477/3405291

**Comment by Micrufun** [comment]
FontAwesome icons are fixed:

image

**Comment by Micrufun** [comment]
Extra buttons are implemented.

# Small screen

Below video:

image

# Large screen

Next to video:

image

**Comment by Micrufun** [comment]
Record button now works:

image

**Comment by Micrufun** [comment]
# Buttons layout

Currently record and stop buttons are next to each other. At the 1st row. Maybe since recording is a focus of the voice artist?

image

**Comment by Micrufun** [comment]
All buttons are working now:

image

**Comment by Micrufun** [comment]
It's tried to develop the DAW component according to ReactJS best practices. 

image

**Comment by Megidd** [comment]
After each commit, the changes so far can be deployed by:
    
```bash
cd /home/mediacms.io/mediacms
docker-compose -f docker-compose-dev.yaml exec -T frontend npm run dist
cp -r frontend/dist/static/* static/
git checkout static/favicons/
git checkout static/images/
git add static/css/ static/js/
git commit
```

**Comment by Megidd** [comment]
while pulling from upstream, if some deployed files like `static/js/_commons.js`, `static/js/embed.js`, `static/js/media.js` have conflict, they can be un-deployed by:

```bash
git checkout upstream/main --  static/js/_commons.js static/js/embed.js static/js/media.js
```
After pulling from upstream and getting latest updates, then, redeployment can be done by the previous comment instructions.

**Pull request merged**
